spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/red-belt

red-belt:
  app:
    jwtSecret: ======================RedBelt=Spring===========================
    jwtExpirationMs: 86400000